name: Sync
on:
  schedule: # every friday at 12:00 UTC
    - cron: "0 12 * * 5"
  workflow_dispatch:
jobs:
  sync-docs:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly
      - uses: Swatinem/rust-cache@v2
      - run: git checkout -b sync-docs
      - name: Sync Docs
        run: cargo xtask overview
      - run: |
          git config user.name ${{github.actor}}
          git config user.email "${{github.actor_id}}+${{github.actor}}@users.noreply.github.com"
      - run: git add .
      - run: >
          git commit -m "docs: sync docs"
      - run: git push origin sync-docs --force
      - run: gh pr list --state open --base main --head sync-docs --json "id" | jq --exit-status 'length == 0'
        continue-on-error: true
        id: pr-list
        env:
          GH_TOKEN: ${{ github.token }}
      # if there is a pr already open, skip the following steps
      - run: gh pr create --fill --body "Automatic overview sync" --base main --head sync-docs
        if: steps.pr-list.outcome == 'success'
        env:
          GH_TOKEN: ${{ github.token }}
      - run: gh pr merge --auto --rebase --delete-branch
        if: steps.pr-list.outcome == 'success'
        env:
          GH_TOKEN: ${{ github.token }}
